### PR TITLE
Migrate Fields to React | Part 2

### PR DESCRIPTION
**Pull request by matuzalemsteles**
This PR is the second part of the migration of fields from DDM to React. This PR is on top of that https://github.com/brunobasto/liferay-portal/pull/1113 which is part 1.

- Epic: https://issues.liferay.com/browse/LPS-108464

The Fields that are contained in this PR with the exception of part 1.

- Options ([LPS-108480](https://issues.liferay.com/browse/LPS-108480))
- Geolocation ([LPS-108476](https://issues.liferay.com/browse/LPS-108476))
- DatePicker ([LPS-108470](https://issues.liferay.com/browse/LPS-108470))
- Fieldset ([LPS-108475](https://issues.liferay.com/browse/LPS-108475))
- DocumentLibrary ([LPS-108471](https://issues.liferay.com/browse/LPS-108471))
- LocalizableText ([LPS-110542](https://issues.liferay.com/browse/LPS-110542))
- ImagePicker ([LPS-110541](https://issues.liferay.com/browse/LPS-110541))
- RichText ([LPS-110544](https://issues.liferay.com/browse/LPS-110544))
- Validation ([LPS-108487](https://issues.liferay.com/browse/LPS-108487))
- Select ([LPS-108484](https://issues.liferay.com/browse/LPS-108484))
- JournalArticleSelector ([LPS-111957](https://issues.liferay.com/browse/LPS-111957))
- LayoutSelector ([LPS-111959](https://issues.liferay.com/browse/LPS-111959))

> NOTE: With the exception of the Field Editor, we will test separately. #21

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:bundle

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by diegonvs** [comment]
ci:bundle

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by alexcandidos** [comment]
hi @matuzalemsteles , CRUD App Builder scripts seem to be failing due to not be able to find the following locator when they are trying to click on the Date field to insert a value. `//p[contains(text(),'Date of birth')]/..//input[1]`

;)

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:bundle

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:stop

**Comment by matuzalemsteles** [comment]
Apparently the changes to the LPS-111072 ticket will cause a lot of broken in the CI, so I'm not going to add that to the FieldBase in React.

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @zhangyan0701, can you please analyze the test suite results for forms and app-builder (still running)? https://issues.liferay.com/browse/LPS-112279

Matu suggests test updates to the following since he tested manually and seems to work fine:
- LocalFile.Forms#ReorderFieldOptions (probably because of the React DnD that we are using now in Options)
- LocalFile.Forms#ChangeFieldType (Apparently failing on the master too, it looks like an unrelated bug)
- LocalFile.Forms#EditTranslatedGridField
- LocalFile.Forms#EditFormsConfigurationViaSystemSettings

**Comment by matuzalemsteles** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:app-builder

**Comment by john-co** [comment]
ci:stop

**Comment by zhangyan0701** [comment]
Just start reviewing.

**Comment by zhangyan0701** [comment]
**App Builder Results:**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1121152178

No related failures.

**Forms Results:**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1120509082

**- [Related] - LocalFile.Forms#ChangeFieldType**
The asterisk icon of required field disappears if switch the Required Field toggle after editing the options.
icon-asterisk

**- [Test Fix] - LocalFile.Forms#ReorderFieldOptions**
This should be a Test Fix, the draganddrop function that used in test doesn't work for this case, we can try with another one.

**- Below tests are not related, also failed on upstream:**

- LocalFile.FormsDataProvider#ConfigureAutocompleteWithTextField
- LocalFile.Forms#EditAllFormFieldsTypesUsedBySystemSettings
- LocalFile.Forms#EditTranslatedGridField
- LocalFile.Forms#EditFormsConfigurationViaSystemSettings

**One UI issue that may releated:**
The default field name of the first option isn't removed when click into it.
option field default name

**Comment by matuzalemsteles** [comment]
@zhangyan0701 thanks a lot! Regarding `LocalFile.Forms#ChangeFieldType` can we reproduce on the master? I think this is not related to this PR, Forms has some problem with the sync of the data flow.

**Comment by zhangyan0701** [comment]
Hi @matuzalemsteles I couldn't reproduce `LocalFile.Forms#ChangeFieldType` on master.

I just checked the history of this test, it failed on this PR and [diegonvs/17](https://github.com/diegonvs/liferay-portal/pull/17).

**Comment by matuzalemsteles** [comment]
hey @zhangyan0701 thanks. This PR is working on top of that PR, it depends on some things here. I will check and fix this today.

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:bundle

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by matuzalemsteles** [comment]
Rebase error on brian's branch 😞, resending at #32

**Pull request closed without merging**
