### PR TITLE
LPS-96323 Provides default userColorCssClass

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @matuzalemsteles, I'm sending this one back to you so you can double check the solution. I think this should be enough to properly provide the default colours to user-based cards.

/cc @mateomustapic

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Just started reviewing :)

**Comment by matuzalemsteles** [comment]
hey @jbalsas sounds good, great idea.

I think I would just change `context.get` from `userCssColorClass` to `userColorClass`:
https://github.com/matuzalemsteles/liferay-portal/blob/405eaa672a0aece14a1748386fbd92c3950a06ab/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/soy/UserCardTag.java#L90

**Comment by jbalsas** [comment]
Ugh, you're right, got confused with what was in `master` and in the PR. 

Can you fix that and send to Brian?

**Comment by matuzalemsteles** [comment]
Sent https://github.com/brianchandotcom/liferay-portal/pull/80816

**Pull request closed without merging**
