### PR TITLE
LPS-108480 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-108480

### CODE REVIEW

**Comment by john-co** [comment]
ci:forward

**Comment by john-co** [comment]
ci:forward

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by john-co** [comment]
@rodrigocunhaa, looks like another flaky test. https://testray.liferay.com/home/-/testray/case_results/1125448034/history?tab=result&hideFilterPin=true

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
I think it would be better to just push directly to BChan. The errors here are confirmed to be unrelated and +60 jobs is quite a chunk of ci resources. However, there seems to be some conflicting files when pushing this PR to BChan's origin...
https://github.com/brianchandotcom/liferay-portal/pull/87951

**Comment by john-co** [comment]
image

**Comment by matuzalemsteles** [comment]
Hey @john-co probably new things came in today 😞 that breaks some part of the migration, I will resolve these conflicts!

**Comment by matuzalemsteles** [comment]
hey @john-co I resolved conflicts, see #34. I'll try ci:forward.

**Pull request closed without merging**
