### PR TITLE
LPS-112425 Migrate FormRenderer.soy and FormRenderer.es.js to React

### PR DESCRIPTION
**Pull request by matuzalemsteles**
This is a part of the FormRenderer migration but it depends on #37 and also on the `withStore` migration for everything to work well.

Some important changes here that were made on top of the #37 changes, FYI this PR is above PR #37, it is simply to create the `useForm` hook in conjunction with the `FormProvider` just responsible for the propagation of events, removed from the `PageProvider`. Some explanations for this are in the commits.

One point about these changes is that it allows for some flexibility in the current structure to allow applications that depend on it to be able to build above the primitive components of Forms, for example:

- Use `FormRenderer` and `FormProvider` to render a form pages and handle events.
- Use `PageRenderer` and `FormProvider` to render just one page and handle events.

Another important thing is that this is not yet functional, it depends on migrating `withStore` because it is a HOC for `FormRenderer.es` and it depended on the Metal + Soy structure, with the Adapter of the Metal for React changes to Metal + JSX this implies some things. I will add the changes to `withStore` in this PR tomorrow.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
There are a lot of interesting changes here, there is still work to be done here and these changes are to remove the current implementation of FormRenderer `withStore`, a lot of it has already been done here but it is still necessary to polish, test and make changes elsewhere. It is also likely that some changes that I have in mind improve the performance of Forms (I'll do some tests with some metrics and make comparisons later.).

On Monday I'm going to push more stuff and I'm going to add a more detailed description of what was done.

**Comment by matuzalemsteles** [comment]
cc @interaminense @kevenleone @alinedoleron @oliveiraaraujo Just to keep you informed, these are the last changes that will end the migration of the FormRenderer (https://issues.liferay.com/browse/LPS-112416), there are two tickets here that I will send together, there is still a work to do refinement in some corrections in some components, I will still leave a detailed description of the changes, the data flow, loading fields, backward compatibility with Metal+Soy and some thoughts about future decoupling that you should have in mind.

**Comment by kevenleone** [comment]
Thanks for keep us informed @matuzalemsteles

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:sf

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:forms

**Comment by matuzalemsteles** [comment]
ci:test:app-builder

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
Creating another PR with more details.

**Comment by matuzalemsteles** [comment]
New PR #49

**Pull request closed without merging**
