### PR TITLE
LPS-112546 fixes syntax error the string literal that causes error in the minifier

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:test:relevant

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by jpince** [comment]
@yichenroy @pyoo47 first `ci:forward` didn't work. Also a case where the amount of time the PR was open is irrelevant (since `ci:forward` wasn't invoked until the day after `relevant` passed). This could also be the case where a PR is sent for review - the sender might invoke `relevant`, but the reviewer might not forward until 1+ days later. I think we should measure 1) number of `ci:forward` attempts and 2) time gap between first `ci:forward` and PR to Brian.

**Comment by yichenroy** [comment]
@jpince @matuzalemsteles the first `ci:forward` didn't work due to this:
https://issues.liferay.com/browse/LRCI-1249

That is a fair point, we'll measure according to those criteria.

**Pull request closed without merging**
