### PR TITLE
Migrate Fields to React | Part 2

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by matuzalemsteles** [comment]
ci:forward

**Comment by john-co** [comment]
The failing test is unrelated. I'll need to update test.properties to avoid it.

**Comment by matuzalemsteles** [comment]
hey @john-co these flaws are probably because other commits appeared in this PR? I updated my master branch so that `ci:test:relevant` can run only the "relevant" tests for this PR.

**Comment by john-co** [comment]
@matuzalemsteles that could be...
@rodrigocunhaa @david-gutierrez-mesa, this may be a flaky test. WorkflowadminCPWebcontent#ApproveInWCSubfolderWorkflow Could someone look into this? https://testray.liferay.com/home/-/testray/cases/865145746

**Comment by john-co** [comment]
quarantining flaky test in https://github.com/matuzalemsteles/liferay-portal/pull/33

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:stop

**Comment by matuzalemsteles** [comment]
Thanks @john-co

**Comment by rodrigocunhaa** [comment]
Yes, it's flaky. Thank you for quarantining it @john-co!

**Pull request closed without merging**
